
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module muxReg(

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
reg mux_output;
assign LEDR[0] = mux_output;


//=======================================================
//  Structural coding
//=======================================================
always@(SW) begin
	if(SW[0]) begin
		mux_output = SW[2];
	end
	else begin
		mux_output = SW[1];
	end
end




endmodule
