
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module bcd2driverTOP(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

bcd2driver bcd2driver(
	.in(SW[6:0]),
	.out0(HEX0),
	.out1(HEX1),
	.gt99(LEDR[0])
);


//=======================================================
//  Structural coding
//=======================================================
assign HEX0[7] = 1'b1;
assign HEX1[7] = 1'b1;
assign HEX2 = 8'hff;
assign HEX3 = 8'hff;
assign HEX4 = 8'hff;
assign HEX5 = 8'hff;

endmodule
