
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module top_clock(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);


//registers
reg KEY0_r;
reg [9:0] SW_r;

always @(posedge MAX10_CLK1_50) begin
  KEY0_r <= #1 KEY[0];
  SW_r[0] <= #1 SW[0];
  SW_r[1] <= #1 SW[1];
  SW_r[2] <= #1 SW[2];
  SW_r[3] <= #1 SW[3];
  SW_r[4] <= #1 SW[4];
  SW_r[5] <= #1 SW[5];
  SW_r[6] <= #1 SW[6];
  SW_r[7] <= #1 SW[7];
  SW_r[8] <= #1 SW[8];
  SW_r[9] <= #1 SW[9];
end

//parameter M50 = 26'b10_1111_1010_1111_0000_1000_0000;
//parameter M05 = 26'b00_0100_1100_0100_1011_0100_0000;

pulse sec(MAX10_CLK1_50, ~KEY0_r, 26'b10_1111_1010_1111_0000_1000_0000, LEDR[9]);

pulse sec_10(MAX10_CLK1_50, ~KEY0_r, 26'b00_0100_1100_0100_1011_0100_0000, LEDR[8]);

pulse sec_20(MAX10_CLK1_50, ~KEY0_r,  26'b00_0000_0000_0100_0000_0000_0010, LEDR[7]);


assign LEDR[0] = ~KEY0_r;
endmodule
